# SuperCodex 프로젝트 설정
# 사용자: (USERPROFILE 기반)
# 프로젝트: agents-workspace

# 신뢰 프로젝트
[projects."%USERPROFILE%"]
trust_level = "trusted"

[projects."%USERPROFILE%\\agents-workspace"]
trust_level = "trusted"

# 승인 정책 및 샌드박스
approval_policy = "never"
sandbox_mode = "workspace-write"

[sandbox_workspace_write]
network_access = true

# --- MCP Servers ---

[mcp_servers.filesystem]
command = "cmd"
args = [
  "/c", "npx", "-y", "@modelcontextprotocol/server-filesystem",
  "--root", "%USERPROFILE%/agents-workspace",
  "--root", "%USERPROFILE%/.claude",
  "--root", "%USERPROFILE%/.gemini"
]

[mcp_servers.sequential]
command = "cmd"
args = ["/c", "npx", "-y", "@modelcontextprotocol/server-sequential-thinking"]

[mcp_servers.playwright]
command = "cmd"
args = ["/c", "npx", "-y", "@playwright/mcp"]

[mcp_servers.context7]
command = "cmd"
args = ["/c", "npx", "-y", "@upstash/context7-mcp"]

[mcp_servers.serena]
command = "serena-mcp-server.exe"
args = []
env = { PATH = "%USERPROFILE%\\.local\\bin;%PATH%" }
